### ISSUE TITLE
Thanks!! sorry but I think example is hard to understand

### ISSUE THREAD

**Issue by yunchiri** [edopelawi/CascadingTableDelegate#11]
I think example is already cascading each section , so clean 

but why each section has viewmodel ?

I think no viewModel is better clean in this example

section , sectionViewModel
row , rowViewModel
many files 
and don't know what is pros 

really sorry
I don't know well
why use view model?
could you teach me?

sorry english^^
happy day!!

**Comment by edopelawi** [comment]
Hi @yunchiri ! Thanks for taking a look at CascadingTableDelegate :) 

Hmm, I didn't realized that my sample was that hard to understand... the `viewModel` was there to provide the data will be shown by each delegate. This is taken from the [MVVM / Model-View-ViewModel architecture](https://en.wikipedia.org/wiki/Model–view–viewmodel) which is commonly used in UI-heavy applications. 

A lot of iOS devs (including me) uses MVVM on their apps because it offers better separation of concern between UI-related code (View), business logic code (Model), and code for transforming the business data to UI-related data (View Model). In the sample, the "delegates" serves as View (in MVVM sense), since their concerns were the display of corresponding section or row they represent.  These delegates use the information from their "view models" to know what data should be shown - e.g. the image in one of the cells.

Of course, you could use this library without conforming to MVVM - it's architecture-agnostic 😄 but if you want to know further about MVVM in iOS, there are plenty of resources in the internet - I learned it from [this objc.io's article back on Obj-C days](https://www.objc.io/issues/13-architecture/mvvm/), but I believe you could find great articles about MVVM in iOS with Swift, too 🙂

**Comment by yunchiri** [comment]
Thanks for reply!! 
good day!! @edopelawi

**Comment by edopelawi** [comment]
No prob, @yunchiri! hope it helps! 😄
